date.timezone = UTC
session.auto_start = Off
short_open_tag = Off
memory_limit = 512M
expose_php = Off

# Error Reporting and Logging
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /dev/stderr

# Output Buffering
output_buffering = Off

# File Uploads and Execution Time
upload_max_filesize = 7M
post_max_size = 40M
max_execution_time = 300
max_input_time = 60