services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Letkode\QueryFilterBundle\EventListener\UndeclaredQueryParameterListener:
        tags:
            - name: kernel.event_listener
              event: kernel.exception
              method: __invoke
              priority: 10
